### ISSUE TITLE
Automatic tube width calculation

### ISSUE THREAD

**Issue by kig** [gl-vis/gl-streamtube3d#2]
Now the tubes require an explicit width param to set their scale. It'd be better if you could scale the tube width automatically so that the widest radius of a tube doesn't overlap other tubes on the starting positions grid.

How to do? When building the tubes, keep track of the max divergence encountered, use that to calculate the divergence scaling factor. Radius = divergence/maxDivergence would get you radius of 1 for max divergence. Multiply that by the minimum distance between starting grid positions to get a tube where the max radius touches the next starting position. Further halve the scale and adjacent max radius tubes wouldn't overlap. Scale = 0.5 * minDistance * divergence / maxDivergence.

**Comment by etpinard** [comment]
Quick question for you @kig : what happens to the default `tubeSize` on divergence-less vector fields (e.g. solenoidal fields)?
