### ISSUE TITLE
Dependencies should be explicitly set in package.json

### ISSUE THREAD

**Issue by wolfd** [gl-vis/gl-streamtube3d#9]
Everything directly imported by a file should have a package version set in `package.json`.
I use pnpm, which disallows relying on phantom dependencies, which causes this package to not work correctly.
For more info on phantom dependencies: https://rushjs.io/pages/advanced/phantom_deps/

https://github.com/gl-vis/gl-streamtube3d/blob/master/lib/tubemesh.js#L6-L16

The dependencies that should be added to `"dependencies"` in `package.json` are:

- `colormap`
- `gl-buffer`
- `gl-mat4`
- `gl-shader`
- `gl-texture2d`
- `gl-vao`
- `gl-vec4`
- `ndarray`
- `normals`
- `simplicial-complex-contour`
- `typedarray-pool`

**Comment by dy** [comment]
@archmoj ping. Not willing to break something

**Comment by archmoj** [comment]
Done in 88be92b5078400752aeaecb3313333196d6870a9 and 5b5a192bbdb436c5f85ed621033574ff16a7c40e. 
Published v.1.3.0 
cc: @etpinard

**Comment by wolfd** [comment]
Thanks for being so quick to look at this!

I'm not sure the issue is entirely resolved, though:
- `gl-mat4` is in `devDependencies` instead of `dependencies`, which is breaking pnpm installs, as it assumes that `devDependencies` are required only when developing the library, and not when just running it.
- `gl-vec4` is missing from both lists, but should go into `dependencies`, as it is directly imported by the library.

Thanks again!

**Comment by archmoj** [comment]
@wolfd is it only `gl-streamtube3d` that needs a second patch? Or `gl-cone3d` should be also revised in this regard?

**Comment by wolfd** [comment]
From what I'm seeing, `gl-cone3d` also needs `gl-mat4` in `dependencies`, but I don't see `gl-vec4` being required anywhere.

**Comment by archmoj** [comment]
@wolfd 
Now published: {
```
  "gl-streamtube3d": "^1.3.1", 
  "gl-cone3d": "^1.4.1",
```
}
